name: Mirroring

on: [push, delete, workflow_dispatch]

jobs:
  to_lsposed:
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: w311ang/repository-mirroring-action-without-tags@master
        with:
          target_repo_url:
            git@github.com:Xposed-Modules-Repo/com.w311ang.disable_flag_keep_screen_on.git
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.LSPOSED_SSH_PRIVATE_KEY }}
